---
dist: trusty
addons:
  apt:
    packages: docker-ce
cache:
  directories:
  - "$HOME/urho3d_home_dir/.ccache"
  - "$HOME/urho3d_home_dir/.emscripten_cache"
  - "$HOME/urho3d_home_dir/initial-build-tree"
env:
  global:
  - secure: SLJCjkjDsTMbCIV9Wecz5JATnhk0fuzlnLMeZdvvFDv+8NL8cXyutkU0VfyRSLf3HSD1Js79a6fRMROyVGWj/w/BRrjqGnZzsB6+ZeJNnadiVIF5Gh+w90We5ccvSp2G4DyYgwkNnkKlJK7zNEWGu/K+bHL1EOCA+EIVrFMyA44=
  - secure: ecj/PwpbHkH9AYFsc2TMeRuNm5E3xMM8A0x4AcGhzpwDuZWdFx3R1T4G9u45Z5aUyTJWGqOeX1JPaEVVFZuYnNBKRy0kmiUrM9EE0j7WsT57K48tP1ysn2ynyvHgbYkKOfYR0t8XAMWTBbulT9DVVk3DS69//2WgiXGDVUEJTyI=
  - numjobs=2
  - WEB=1
  - EMSCRIPTEN_SHARE_DATA=1
  - HOT=/home/travis/urho3d_home_dir/.ccache/.hot
  matrix:
  - URHO3D_LIB_TYPE=MODULE EMSCRIPTEN_WASM=0 numjobs=4
  - URHO3D_LIB_TYPE=STATIC EMSCRIPTEN_WASM=0
  - URHO3D_LIB_TYPE=SHARED EMSCRIPTEN_WASM=0
  - URHO3D_LIB_TYPE=STATIC
  - URHO3D_LIB_TYPE=SHARED
stage: release build configuration
before_script:
- rake ci_timer
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- export TAG=$(git describe --exact-match $TRAVIS_COMMIT 2>/dev/null); if [[ $TAG
  =~ [[:digit:]]+\.[[:digit:]]+ ]]; then export RELEASE_TAG=$TAG; fi
- if [[ $RELEASE_TAG ]] || (! [[ $TRAVIS_BRANCH =~ [^-]+-[^-]+-CI ]] && echo $COMMIT_MESSAGE
  |grep -cq '\[ci package\]'); then export PACKAGE_UPLOAD=1; fi
- if [[ "$URHO3D_LIB_TYPE" != "MODULE" ]] && (echo $COMMIT_MESSAGE |grep -cq '\[cache
  clear\]' || [[ ! -e $HOT ]]); then export URHO3D_SAMPLES=0; else export URHO3D_SAMPLES=1;
  fi; touch $HOT
- rake ci_setup_cache
script: script/dockerized.sh web rake ci && if [ $PACKAGE_UPLOAD ]; then script/dockerized.sh
  web rake ci_package_upload; fi && if [[ "$TRAVIS_BRANCH" == "Web-CI" ]] && [[ !
  $EMSCRIPTEN_WASM ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$URHO3D_LIB_TYPE"
  == "SHARED" ]] && [[ ! $URHO3D_SAMPLES ]]; then script/dockerized.sh web rake ci_emscripten_samples_update;
  fi && rake ci_timer
matrix:
  fast_finish: true
  include:
  - stage: housekeep
    addons: 
    before_script: export TAG=$(git describe --exact-match $TRAVIS_COMMIT~ 2>/dev/null);
      if [[ $TAG =~ [[:digit:]]+\.[[:digit:]]+ ]]; then export RELEASE_TAG=$TAG; fi
    after_script: 
    cache: 
    before_cache: 
    env: 
    script: rake ci_delete_mirror
data:
  excluded_sample:
    "#4": &1
    - 01_HelloWorld
    - 02_HelloGUI
    - 03_Sprites
    - 26_ConsoleInput
    - 29_SoundSynthesis
    - 38_SceneAndUILoad
    "#5": *1
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
    - arnis.lielturks@gmail.com
